; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 115200
src_filter = +<*.h> +<main-${PIOENV}.cpp>

; platform = https://github.com/mnowak32/platform-espressif32.git#boards/seeed_xiao_esp32c6
; platform_packages = 
;     framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.2
;     framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.2/esp32-arduino-libs-3.0.2.zip
; board = seeed_xiao_esp32c6


platform = espressif32
;board = seeed_xiao_esp32s3
board = esp32dev
board_build.flash_mode = dio #effective for boot loop trap


[env:basic]
[env:BLE-GATT]
[env:BLE]
[env:WiFi]
[env:BME]
lib_deps = 
	adafruit/Adafruit BME280 Library@^2.2.4
[env:BMP]
lib_deps= adafruit/Adafruit BMP280 Library @ ^2.6.8

[env:MPU]
lib_deps = hideakitai/MPU9250@^0.4.8

[env:led]
lib_deps = adafruit/Adafruit LED Backpack Library@^1.5.1
[env:i2cScan]
[env:OLED]
lib_deps =   adafruit/Adafruit SSD1306 @ ^2.5.13
[env:CAM]
lib_deps = espressif/esp32-camera @ ^2.0.4
[env:A2DP]
lib_deps = 
    git+https://github.com/pschatzmann/ESP32-A2DP 
    git+https://github.com/pschatzmann/arduino-audio-tools.git
    esphome/ESP32-audioI2S @ ^2.0.7


